name: Igor
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ambertools=23
  - openmm==8.2.0
  - psfgen
  - pip
  - pip:
    - -r requirements.txt
  # External Software (manual installation required):
  #  - orca # Quantum chemistry software, see official website for installation
  #  - multiwfn # Wavefunction analysis software, see official website for installation